// Regenerates hooks/logos.ts from Simple Icons (CC0 icon data; each logo is
// its brand owner's trademark). Run from the plugin folder:
//   node scripts/fetch-logos.mjs
// It reads the slugs listed in hooks/brands.ts, fetches each icon's SVG and
// the package's colour data from jsDelivr at one pinned version, and writes
// only the brands Simple Icons has; the rest keep the neutral plug mark.

import { readFileSync, writeFileSync } from 'node:fs'

const VERSION = '16.32.0'
const BASE = `https://cdn.jsdelivr.net/npm/simple-icons@${VERSION}`

const slugs = [...readFileSync('hooks/brands.ts', 'utf8').matchAll(/slug: '([a-z0-9]+)'/g)].map(m => m[1])

// Simple Icons' own title-to-slug rule.
const titleToSlug = title =>
  title
    .toLowerCase()
    .replaceAll('+', 'plus')
    .replaceAll('.', 'dot')
    .replaceAll('&', 'and')
    .replaceAll('đ', 'd')
    .replaceAll('ħ', 'h')
    .replaceAll('ı', 'i')
    .replaceAll('ĸ', 'k')
    .replaceAll('ŀ', 'l')
    .replaceAll('ł', 'l')
    .replaceAll('ß', 'ss')
    .replaceAll('ŧ', 't')
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]/g, '')

const dataResponse = await fetch(`${BASE}/data/simple-icons.json`)
if (!dataResponse.ok) throw new Error(`colour data: HTTP ${dataResponse.status}`)
const data = await dataResponse.json()
const icons = Array.isArray(data) ? data : data.icons
const bySlug = new Map(icons.map(icon => [icon.slug ?? titleToSlug(icon.title), icon]))

const logos = {}
const missing = []
for (const slug of slugs) {
  const icon = bySlug.get(slug)
  const svg = icon === undefined ? undefined : await fetch(`${BASE}/icons/${slug}.svg`)
  if (icon === undefined || svg === undefined || !svg.ok) {
    missing.push(slug)
    continue
  }
  const text = await svg.text()
  const path = text.match(/<path d="([^"]+)"/)?.[1]
  if (path === undefined) {
    missing.push(slug)
    continue
  }
  logos[slug] = { title: icon.title, hex: icon.hex.toUpperCase(), path }
}

writeFileSync(
  'hooks/logos.ts',
  `// Generated by scripts/fetch-logos.mjs from Simple Icons ${VERSION} (CC0-1.0 icon data).\n` +
    `// Each logo is a trademark of its owner, used here only to name their plugin.\n` +
    `export const LOGOS: Record<string, { title: string; hex: string; path: string }> = ${JSON.stringify(logos, null, 2)}\n`,
)
console.log(`wrote ${Object.keys(logos).length} logos; not in Simple Icons ${VERSION}: ${missing.join(', ') || 'none'}`)
